name: get_trial.py
on:
  workflow_dispatch:
  schedule:
    - cron: '3/5 * * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    concurrency: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Prepare
        run: |
          sudo chmod 777 $CHROMEWEBDRIVER/chromedriver
          pip install requests beautifulsoup4 undetected-chromedriver
      - name: Run get_trial.py
        run: xvfb-run --auto-servernum python get_trial.py
      - name: Commit
        id: commit
        continue-on-error: true
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "${{ github.workflow }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          git pull --rebase
      - uses: ad-m/github-push-action@master
        if: ${{ steps.commit.outcome == 'success' }}
